language: node_js
env: CI=true
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "iojs"
  - "0.12"
after_script:
  - npm run coveralls
  - git config --global alias.co checkout
  - ./publish_docs.sh
notifications:
  email:
    - ismar@slomic.no

